### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by mml1** [jahdroid/codecademy-project-3-the-scoop#4]
(Subtlety) There is a minor bug when a user upvotes a comment and then downvotes a comment. Instead of changing the votes by 1, the vote is changed by 2. Can you reproduce this error? If so, I think you can debug it.

**Comment by jahdroid** [comment]
Okay I will look at it...

**Comment by jahdroid** [comment]
I think that works as expected... Because the upvotes are subtracted by the downvotes.

*Case 1:*
 * If a comment is new and no one has yet up or downvoted the comment, its vote is 0.
 * If user1 upvotes the comment, its vote becomes 1.
 * If user1 downvotes the comment, its vote becomes -1.

*Case 2:*
 * If a comment is new and only user1 has upvoted the comment, its vote is 1.
 * If user2 now upvotes the comment, its vote becomes 2.
 * If user2 downvotes the comment, its vote becomes 0.

I retested all cases described above and think this works as designed.
Also the introduction video demonstrates the same behaviour.
Therefore I will not provide a Bugfix :innocent:

**Comment by mml1** [comment]
Great work! Your explanation is very clear too. Keep it up.
